//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class cutting
    {
        public int code { get; set; }
        public int id_fabric_warehouse { get; set; }
        public int code_order { get; set; }
        public double width { get; set; }
        public double length { get; set; }
        public int count { get; set; }
    
        public virtual fabric_warehouse fabric_warehouse { get; set; }
        public virtual order order { get; set; }
    }
}
